---
title: "Smoking"
format: html
editor: visual
execute: 
  warning: false
---

```{r}
#| label: setup
#| include: false


needs(tidyverse, data.table, googledrive, readxl, skimr, janitor, gt, gtsummary, collapsibleTree, PHEindicatormethods, ggthemes, sf, tmap, ggspatial, curl, raster, stars)

theme_set(ggthemes::theme_economist())

dir <- here::here("~/s/data/fwdatastrategypocpublichealthframeworkindicators")

smoking <-  smoking |> setDT()


```

### Data preparation

#### load census population  and create age bands

```{r}
#| label: pop data

pops <- setDT(dfs1$pop)[, `:=` (five_year = cut(age, breaks = seq(0, 100, 5), right = FALSE), `18-44` = between(age, 18, 44), `15+` = age >= 15)][]

pop_agg <- pops[, .(n = .N, sumpops = sum(Population, na.rm = TRUE)), by = .(Region, five_year, `18-44`, `15+`,  Gender)]

```

#### load smoking data and create age bands

```{r}
#| label: create age bands - 5 yr, 18-44, 15+

smoking <- smoking[, `:=` (five_year = cut(age, breaks = seq(0, 100, 5), right = FALSE), `18-44` = between(age, 18, 44), `15+` = age >= 15)][]

smoking[, .N, by = .(Region, age, Gender)]

```

#### join datasets

```{r}
#| label: join data

smoking[, age := NULL][] |>
  full_join(pop_agg, by = c("Region", "five_year", "Gender")) |>
  arrange(Gender)

```

