{
  "hash": "74959fb04fcbe5f79dc8ccb510ebb45e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Injury\"\nformat: \n   html: \n      toc: true\n      toc-location: right\neditor: visual\nexecute: \n  echo: false\n  output: true\n  warning: false\n  message: false\n---\n\n\n## Injury\n\nFirst, load injury and population data\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  DateOfBirth                          code            diagnosis        \n Min.   :1939-08-16 00:00:00.000   Length:10380       Length:10380      \n 1st Qu.:1970-10-10 00:00:00.000   Class :character   Class :character  \n Median :1985-11-10 00:00:00.000   Mode  :character   Mode  :character  \n Mean   :1984-01-01 12:27:30.296                                        \n 3rd Qu.:1996-07-05 00:00:00.000                                        \n Max.   :2022-01-30 00:00:00.000                                        \n NA's   :773                                                            \n    Gender             Region               age     \n Length:10380       Length:10380       Min.   : 1   \n Class :character   Class :character   1st Qu.:27   \n Mode  :character   Mode  :character   Median :38   \n                                       Mean   :39   \n                                       3rd Qu.:53   \n                                       Max.   :84   \n                                       NA's   :773  \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Age distribution of injury admissions](injury_files/figure-html/fig-agehist-1.png){#fig-agehist width=672}\n:::\n:::\n\n\nOverall there are 10380 records, of which 773 (7.45% ) have missing dates of of birth. These are excluded from analyis\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\nThe data contains values for 12 of the 13 regions.\n\n\n::: {.cell}\n\n:::\n\n\n## Aggregate injury data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-48ea4de2{}.cl-48e551ac{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48e7556a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-48e75574{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-48e7651e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48e7651f{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48e76528{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48e76529{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48e7652a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48e76532{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-48ea4de2'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-48e7651e\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Region</span></p></th><th class=\"cl-48e7651e\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">diagnosis</span></p></th><th class=\"cl-48e7651e\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">code</span></p></th><th class=\"cl-48e7651e\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">age_band</span></p></th><th class=\"cl-48e7651f\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">Female</span></p></th><th class=\"cl-48e7651f\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">Male</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Makkah</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Open wound of head</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">S01</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">[25,30)</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\"></span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">20</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Northern Frontier</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Open wound of head</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">S01</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">[20,25)</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">15</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Northern Frontier</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Open wound of head</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">S01</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">[25,30)</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">10</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Northern Frontier</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Open wound of head</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">S01</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">[30,35)</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">16</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Northern Frontier</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Open wound of head</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">S01</span></p></td><td class=\"cl-48e76528\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">[35,40)</span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\"></span></p></td><td class=\"cl-48e76529\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-48e7652a\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Northern Frontier</span></p></td><td class=\"cl-48e7652a\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">Open wound of head</span></p></td><td class=\"cl-48e7652a\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">S01</span></p></td><td class=\"cl-48e7652a\"><p class=\"cl-48e7556a\"><span class=\"cl-48e551ac\">[40,45)</span></p></td><td class=\"cl-48e76532\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">8</span></p></td><td class=\"cl-48e76532\"><p class=\"cl-48e75574\"><span class=\"cl-48e551ac\">2</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n## Recode region names to match census names\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Al Jawf\" \"Jazan\"   \"Najran\" \n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"0-4\"   \"5-9\"   \"10-14\" \"15-19\" \"20-24\" \"25-29\" \"30-34\" \"35-39\" \"40-44\"\n[10] \"45-49\" \"50-54\" \"55-59\" \"60-64\" \"65-69\" \"70-74\" \"75-79\" \"80+\"  \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] [40,45) [70,75) [35,40) [65,70) [15,20) [80,85) [55,60) [25,30) [30,35)\n[10] [60,65) [50,55) [0,5)   [45,50) [10,15) [20,25) [75,80)\n24 Levels: [0,5) [5,10) [10,15) [15,20) [20,25) [25,30) [30,35) ... [115,120)\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0-4   5-9   10-14 15-19 20-24 25-29 30-34 35-39 40-44 45-49 50-54 55-59\n[13] 60-64 65-69 70-74 75-79 80+  \n17 Levels: 0-4 5-9 10-14 15-19 20-24 25-29 30-34 35-39 40-44 45-49 ... 80+\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n## Calculate directly age standardised rates for injury admission by region and gender\n\nUse `epitools::ageadjust.direct`.\n\nTo iterate over regions and gender we'll split by gender and use the `nest_by` function to group data by region and apply standardiastion function.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Age standardised injury admission rate per 100,000 by region and gender](injury_files/figure-html/fig-dsr-1.png){#fig-dsr width=672}\n:::\n:::\n",
    "supporting": [
      "injury_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}